<?php
vc_map(array(
    "name" 			=> "Promo Block",
    "category" 		=> 'VC Addons',
    "description"	=> "Multi-purpose block with content, background, fullwidth and parallax options",
    "base" 			=> "asvc_promo_block",
    "class" 			=> "",
    "icon" 			=> "asvc_promo_block_icon",
    
    "params" 	=> array(
    
    
                    array(
                        "type" => "hvc_notice",
                        "class" => "",
                        'heading' => __('<h3 class="hvc_notice" align="center">This is premium addon, please buy the pro version here <a target="_blank" href="https://codenpy.com/item/visual-composer-shortcodes-pro/">Essential WPBakery Page Builder (formerly Visual Composer) Addons</a> for only $13</h3>', 'hvc'),
                        "param_name" => "hvc_notice_param_1",
                        "value" => '',
                    ),    
    		array(
            "type"			=> "mgt_separator",
            "heading" => "Background color settings",
            "param_name"	=> generate_separator_name(),
        ),
    		array(
            "type"			=> "colorpicker",
            ////"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Background color",
            "param_name"	=> "background_color",
            "std"			=> "#F5F5F5",
        ),
        array(
            "type"			=> "dropdown",
            ////"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Overlay block content with semi-transparent background",
            "param_name"	=> "darken",
            "value"			=> array(
                "Yes"	=> "darken",
                "No"	=> "no-darken"
            ),
            "description"	=> "Use this option if you have light background image and want to show light text on it.",
            "std"			=> "no-darken",
        ),
        array(
            "type"			=> "colorpicker",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Overlay color",
            "param_name"	=> "darken_overlay_color",
            "dependency"	=> array(
                "element"	=> "darken",
                "value"		=> Array("darken"),
            ),
            "std"			=> "rgba(0,0,0,0.3)",
            "description"	=> "Choose color with Alpha property to make overlay semi-transparent.",
        ),
        array(
            "type"			=> "dropdown",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Overlay block content with semi-transparent background on hover.",
            "param_name"	=> "animated",
            "value"			=> array(
                "Yes"	=> "1",
                "No"	=> "0"
            ),
            "description"	=> "Block background will fade to selected color on block mouse hover.",
            "std"			=> "0",
        ),
        array(
            "type"			=> "colorpicker",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Overlay color for hover",
            "param_name"	=> "animated_overlay_color",
            "dependency"	=> array(
                "element"	=> "animated",
                "value"		=> Array("1"),
            ),
            "std"			=> "rgba(0, 0, 0, 0.5)",
            "description"	=> "Choose color with Alpha property to make overlay semi-transparent.",
        ),
        array(
            "type"			=> "mgt_separator",
            "param_name"	=> generate_separator_name(),
            "heading"		=> "Background image settings",
        ),
        array(
            'type' => 'checkbox',
            'heading' => __( 'Add background image?', 'js_composer' ),
            'param_name' => 'background_image_enable',
        ),
    		array(
            "type"			=> "attach_image",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Background image",
            "param_name"	=> "background_image_id",
            "std"			=> "",
            'dependency' => array(
                'element' => 'background_image_enable',
                'value' => 'true',
            ),
        ),
        array(
            "type"			=> "dropdown",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Background image repeat",
            "description"	=> "Use if you use pattern background image.",
            "param_name"	=> "background_repeat",
            "value"			=> array(
                "No repeat"	=> "no-repeat",
                "Repeat"	=> "repeat",
                "Repeat X"	=> "repeat-x",
                "Repeat Y"	=> "repeat-y"
            ),
            "std"			=> "no-repeat",
            'dependency' => array(
                'element' => 'background_image_enable',
                'value' => 'true',
            ),
            "edit_field_class" => "vc_col-xs-6",
        ),
        array(
            "type"			=> "dropdown",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Background image cover",
            "description"	=> "If enabled background image will fit block by width.",
            "dependency"	=> array(
                "element"	=> "parallax",
                "value"		=> Array("0"),
            ),
            "param_name"	=> "coverimage",
            "value"			=> array(
                "Yes"	=> "1",
                "No"	=> "0"
            ),
            "std"			=> "0",
            'dependency' => array(
                'element' => 'background_image_enable',
                'value' => 'true',
            ),
            "edit_field_class" => "vc_col-xs-6",
        ),
        array(
            "type"			=> "dropdown",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Background image parallax",
            "description"	=> "Use background image with height few more than block height for correct parallax work.",
            "param_name"	=> "parallax",
            "value"			=> array(
                "None"	=> "",
                "Simple"	=> "fixed",
                "With fade"	=> "fade"
            ),
            "std"			=> "",
            'dependency' => array(
                'element' => 'background_image_enable',
                'value' => 'true',
            ),
            "edit_field_class" => "vc_col-xs-6",
        ),
        array(
            "type"			=> "textfield",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Parallax speed",
            "description"	=> "Enter parallax speed ratio (Note: Default value is 1.5, min value is 1)",
            "param_name"	=> "parallax_speed",
            "std"			=> "1.5",
            'dependency' => array(
                'element' => 'background_image_enable',
                'value' => 'true',
            ),
            "edit_field_class" => "vc_col-xs-6",
        ),
        array(
            'type' => 'checkbox',
            'heading' => __( 'Use video background?', 'js_composer' ),
            'param_name' => 'video_bg',
            "description"	=> "If checked, video will be used as block content background.",
        ),
        array(
            "type"			=> "textfield",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "YouTube link",
            "description"	=> "Add YouTube video link. Other video services is not supported.",
            "param_name"	=> "video_bg_url",
            "std"			=> "https://www.youtube.com/watch?v=lMJXxhRFO1k",
            'dependency' => array(
                'element' => 'video_bg',
                'value' => 'true',
            ),
        ),
        /// Block border
        array(
            "type"			=> "mgt_separator",
            "param_name"	=> generate_separator_name(),
            "heading"		=> "Block border settings",
        ),
        array(
            'type' => 'checkbox',
            'heading' => __( 'Add block border?', 'js_composer' ),
            'param_name' => 'block_border',
            "description"	=> "Use this to add border to block.",
        ),
        array(
            "type"			=> "textfield",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Block border width (in pixels)",
            "description"	=> "Add border width here, for example: 3",
            "param_name"	=> "block_border_width",
            "std"			=> "1",
            'dependency' => array(
                'element' => 'block_border',
                'value' => 'true',
            ),
            "edit_field_class" => "vc_col-xs-6",
        ),
        array(
            "type"			=> "dropdown",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Block border style",
            "description"	=> "Select block border style.",
            "param_name"	=> "block_border_style",
            "value"			=> array(
                "Solid"	=> "solid",
                "Dashed"	=> "dashed",
                "Dotted"	=> "dotted",
                "Double"	=> "double",
                "Groove"	=> "groove",
                "Ridge"	=> "ridge",
                "Inset"	=> "inset",
                "Outset"	=> "outset",
            ),
            "std"			=> "solid",
            'dependency' => array(
                'element' => 'block_border',
                'value' => 'true',
            ),
            "edit_field_class" => "vc_col-xs-6",
        ),
        array(
            "type"			=> "colorpicker",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Block border color",
            "param_name"	=> "block_color_border",
            "description"	=> "Select block border color.",
            "std"			=> "",
            'dependency' => array(
                'element' => 'block_border',
                'value' => 'true',
            ),
            "edit_field_class" => "vc_col-xs-6",
        ),
        array(
            "type"			=> "colorpicker",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Block hover border color",
            "param_name"	=> "block_color_borderhover",
            "description"	=> "Select block hover border color.",
            "std"			=> "",
            'dependency' => array(
                'element' => 'block_border',
                'value' => 'true',
            ),
            "edit_field_class" => "vc_col-xs-6",
        ),
        ///
        array(
            "type"			=> "mgt_separator",
            "param_name"	=> generate_separator_name(),
            "heading"		=> "Block and content settings",
        ),
        array(
            "type"			=> "textfield",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Block height (px)",
            "description"	=> "Leave empty to use uploaded background image height or fit to content. For example: 600px",
            "param_name"	=> "block_height",
            "edit_field_class" => "vc_col-xs-6",
            "std"			=> "",
        ),
        array(
            "type"			=> "dropdown",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Block content vertical align",
            "param_name"	=> "content_va",
            "value"			=> array(
                "Top"	=> "top",
                "Middle"	=> "middle",
                "Bottom"	=> "bottom"
            ),
            "edit_field_class" => "vc_col-xs-6",
            "std"			=> "middle",
        ),
        
        array(
            "type"			=> "dropdown",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Text color",
            "description"	=> "Select black color if you use light/white background in block. You can specify custom colors on Format tab.",
            "param_name"	=> "text_color",
            "value"			=> array(
                "Black"	=> "black",
                "White"	=> "white"
            ),
            "std"			=> "black",
            "edit_field_class" => "vc_col-xs-6",
        ),
                array(
            "type"			=> "dropdown",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Text color on block mouse hover",
            "param_name"	=> "text_color_hover",
            "value"			=> array(
                "Change to white"	=> "1",
                "Do not change"	=> "0"
            ),
            "description"	=> "Change text and links color to white on block mouse hover. Useful if you change your block background color to dark on mouse hover.",
            "std"			=> "0",
            "edit_field_class" => "vc_col-xs-6",
        ),
        array(
            "type"			=> "textfield",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Block content link (url)",
            "description"	=> "Add url here if you want to have link for overall block content. If you use this option you must NOT add any links inside block content, because this will break HTML layouts.",
            "param_name"	=> "block_url",
            "std"			=> "",
        ),
        array(
            'type' => 'checkbox',
            'heading' => 'Open block content link in new tab?',
            'param_name' => 'block_url_target_blank',
            "description"	=> "Open link in new browser tab/window.",
        ),
        array(
            "type"			=> "textarea_html",
            //"holder"		=> "div",
            "class" 		=> "mgt-promo-block-content-html",
            "admin_label" 	=> false,
            "heading"		=> "Block content",
            "param_name"	=> "content",
            "std"			=> '',
        ),
        array(
            "type"			=> "mgt_separator",
            "param_name"	=> generate_separator_name(),
            "heading"		=> "Block effects and animations",
        ),
        array(
            'type' => 'checkbox',
            'heading' => __( 'Add block shadow effect?', 'js_composer' ),
            'param_name' => 'block_shadow_effect',
            "description"	=> "Use this to add shadow to overall block.",
            "edit_field_class" => "vc_col-xs-6",
        ),
        array(
            'type' => 'checkbox',
            'heading' => __( 'Add mouse hover block moving effect?', 'js_composer' ),
            'param_name' => 'block_hover_effect',
            "description"	=> "Use this to add block moving effect on block hover.",
            "edit_field_class" => "vc_col-xs-6",
        ),
        array(
            'type' => 'checkbox',
            'heading' => __( 'Show block content only on mouse hover?', 'js_composer' ),
            'param_name' => 'block_content_onhover',
            "description"	=> "Use this to hide block content by default and show it only on block mouse hover.",
        ),
        // CSS Animations
        vc_map_add_css_animation( true ),
        /* Top Image */
        array(
            "type"			=> "mgt_separator",
            "param_name"	=> generate_separator_name(),
            "heading"		=> "Top image settings",
            "group"			=> "Top image",
        ),
        array(
            'type' => 'checkbox',
            'heading' => __( 'Add top image?', 'js_composer' ),
            'param_name' => 'top_image_enable',
            "group"			=> "Top image",
            'description' => __( 'Enable to show image at the top of your promo block (above promo block content).', 'js_composer' ),
        ),
    		array(
            "type"			=> "attach_image",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Top image",
            "param_name"	=> "top_image_id",
            "std"			=> "",
            'dependency' => array(
                'element' => 'top_image_enable',
                'value' => 'true',
            ),
            "group"			=> "Top image",
        ),
        array(
            "type"			=> "colorpicker",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Top image background color",
            "param_name"	=> "top_image_background_color",
            "description"	=> "Use if you have transparent PNG background image",
            'dependency' => array(
                'element' => 'top_image_enable',
                'value' => 'true',
            ),
            "group"			=> "Top image",
            "std"			=> "",
        ),
        array(
            "type"			=> "dropdown",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Background image size",
            "param_name"	=> "top_image_background_size",
            "value"			=> array(
                "Cover all space"	=> "cover",
                "Keep original size"	=> "auto",
            ),
            'dependency' => array(
                'element' => 'top_image_enable',
                'value' => 'true',
            ),
            "group"			=> "Top image",
            "description"	=> "Change background image size.",
            "std"			=> "cover",
            "group"			=> "Top image",
        ),
        array(
            "type"			=> "textfield",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Top image height (px)",
            "description"	=> "Leave empty to use theme predefined top image height (250). Example: 400",
            "param_name"	=> "top_image_height",
            "std"			=> "",
            'dependency' => array(
                'element' => 'top_image_enable',
                'value' => 'true',
            ),
            "group"			=> "Top image",
        ),
        array(
            "type"			=> "textfield",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Top image link (url)",
            "description"	=> "Add url here if you want to have link for top image.",
            "param_name"	=> "top_image_url",
            "std"			=> "",
            'dependency' => array(
                'element' => 'top_image_enable',
                'value' => 'true',
            ),
            "group"			=> "Top image",
        ),
        /* Button */
        array(
            "type"			=> "mgt_separator",
            "param_name"	=> generate_separator_name(),
            "heading"		=> "Button settings",
            "group"			=> "Button",
        ),
        array(
            "type"			=> "vc_link",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Button Text and Link",
            "description"	=> "Button text and url, Leave empty if you don't need button.",
            "param_name"	=> "button_url",
            "std"			=> "",
            "group"			=> "Button",
        ),
        array(
            "type"			=> "dropdown",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Button style",
            "param_name"	=> "button_style",
            "value"			=> array(
                "Default"	=> "solid",
                "Black"	=> "solid-invert",
                "Grey"	=> "grey",
                "Bordered"	=> "bordered",
                "Bordered Black"	=> "borderedblack",
                "Bordered Grey"	=> "borderedgrey",
                "Bordered White"	=> "borderedwhite",
                "Red"	=> "red",
                "Green"	=> "green",
                "Text link dark"	=> "text",
                "Text link light (use on dark backgrounds)"	=> "textwhite"
            ),
            "description"	=> "Change button style",
            "std"			=> "solid",
            "group"			=> "Button",
            "edit_field_class" => "vc_col-xs-6",
        ),
        array(
            "type"			=> "dropdown",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Button round edges",
            "param_name"	=> "button_round_edges",
            "value"			=> array(
                "Disable"	=> "disable",
                "Small"	=> "small",
                "Medium"	=> "medium",
                "Large"	=> "large",
                "Full"	=> "full"
            ),
            "description"	=> "Change button border radius (round edges)",
            "std"			=> "disable",
            "group"			=> "Button",
            "edit_field_class" => "vc_col-xs-6",
        ),
        array(
            "type"			=> "dropdown",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Button size",
            "param_name"	=> "button_size",
            "value"			=> array(
                "Small"	=> "small",
                "Normal"	=> "normal",
                "Large"	=> "large"
            ),
            "description"	=> "",
            "std"			=> "normal",
            "group"			=> "Button",
            "edit_field_class" => "vc_col-xs-6",
        ),
        array(
            "type"			=> "dropdown",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Button horizontal align",
            "param_name"	=> "button_align",
            "value"			=> array(
                "Left"	=> "left",
                "Center"	=> "center",
                "Right"	=> "right"
            ),
            "description"	=> "",
            "std"			=> "center",
            "group"			=> "Button",
            "edit_field_class" => "vc_col-xs-6",
        ),
        array(
            "type"			=> "dropdown",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Button text size",
            "param_name"	=> "button_text_size",
            "value"			=> array(
                "Small"	=> "small",
                "Normal"	=> "normal",
                "Large"	=> "large"
            ),
            "description"	=> "",
            "std"			=> "normal",
            "group"			=> "Button",
            "edit_field_class" => "vc_col-xs-6",
        ),
        array(
            "type"			=> "dropdown",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Button text transform",
            "param_name"	=> "button_text_transform",
            "value"			=> array(
                "None"	=> "none",
                "UPPERCASE"	=> "uppercase"
            ),
            "description"	=> "",
            "std"			=> "none",
            "group"			=> "Button",
            "edit_field_class" => "vc_col-xs-6",
        ),
        array(
            'type' => 'checkbox',
            'heading' => __( 'Add top margin?', 'js_composer' ),
            'param_name' => 'button_top_margin',
            "description"	=> "Use this if you want to add additional space between button and your top content.",
            "group"			=> "Button",
        ),
        // Button icon
        array(
            "type"			=> "mgt_separator",
            "param_name"	=> generate_separator_name(),
            "heading"		=> "Button icon settings",
            "group"			=> "Button",
        ),
        array(
            'type' => 'checkbox',
            'heading' => __( 'Add icon?', 'js_composer' ),
            'param_name' => 'button_icon',
            "group"			=> "Button",
            "edit_field_class" => "vc_col-xs-6",
        ),
        array(
            'type' => 'checkbox',
            'heading' => __( 'Add icon separator line?', 'js_composer' ),
            'param_name' => 'button_icon_separator',
            'dependency' => array(
                'element' => 'button_icon',
                'value' => 'true',
            ),
            "group"			=> "Button",
            "edit_field_class" => "vc_col-xs-6",
        ),
        array(
            "type"			=> "dropdown",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Button icon alignment",
            "param_name"	=> "button_icon_position",
            "value"			=> array(
                "Left"	=> "left",
                "Right"	=> "right"
            ),
            "description"	=> "",
            "std"			=> "left",
            'dependency' => array(
                'element' => 'button_icon',
                'value' => 'true',
            ),
            "group"			=> "Button",
        ),
        array(
            'type' => 'dropdown',
            'heading' => __( 'Icon library', 'js_composer' ),
            'value' => array(
                __( 'Font Awesome', 'js_composer' ) => 'fontawesome',
                __( 'Open Iconic', 'js_composer' ) => 'openiconic',
                __( 'Typicons', 'js_composer' ) => 'typicons',
                __( 'Entypo', 'js_composer' ) => 'entypo',
                __( 'Linecons', 'js_composer' ) => 'linecons',
                __( 'Mono Social', 'js_composer' ) => 'monosocial',
                __( 'Material', 'js_composer' ) => 'material',
            ),
            'dependency' => array(
                'element' => 'button_icon',
                'value' => 'true',
            ),
            //'admin_label' => true,
            'param_name' => 'icon_type',
            'description' => __( 'Select icon library.', 'js_composer' ),
            "std"		=> "fontawesome",
            "group"			=> "Button",
        ),
        array(
            'type' => 'iconpicker',
            'heading' => __( 'Icon', 'js_composer' ),
            'param_name' => 'icon_fontawesome',
            'value' => 'fa fa-adjust',
            // default value to backend editor admin_label
            'settings' => array(
                'emptyIcon' => false,
                // default true, display an "EMPTY" icon?
                'iconsPerPage' => 4000,
                // default 100, how many icons per/page to display, we use (big number) to display all icons in single page
                'type' => 'fontawesome',
            ),
            'dependency' => array(
                'element' => 'icon_type',
                'value' => 'fontawesome',
            ),
            'description' => __( 'Select icon from library.', 'js_composer' ),
            "group"			=> "Button",
        ),
        array(
            'type' => 'iconpicker',
            'heading' => __( 'Icon', 'js_composer' ),
            'param_name' => 'icon_pe7stroke',
            'value' => 'pe-7s-album',
            // default value to backend editor admin_label
            'settings' => array(
                'emptyIcon' => false,
                // default true, display an "EMPTY" icon?
                'iconsPerPage' => 4000,
                'type' => 'pe7stroke',
                // default 100, how many icons per/page to display, we use (big number) to display all icons in single page
            ),
            'dependency' => array(
                'element' => 'icon_type',
                'value' => 'pe7stroke',
            ),
            'description' => __( 'Select icon from library.', 'js_composer' ),
            "group"			=> "Button",
        ),
        array(
            'type' => 'iconpicker',
            'heading' => __( 'Icon', 'js_composer' ),
            'param_name' => 'icon_openiconic',
            'value' => 'vc-oi vc-oi-dial',
            // default value to backend editor admin_label
            'settings' => array(
                'emptyIcon' => false,
                // default true, display an "EMPTY" icon?
                'type' => 'openiconic',
                'iconsPerPage' => 4000,
                // default 100, how many icons per/page to display
            ),
            'dependency' => array(
                'element' => 'icon_type',
                'value' => 'openiconic',
            ),
            'description' => __( 'Select icon from library.', 'js_composer' ),
            "group"			=> "Button",
        ),
        array(
            'type' => 'iconpicker',
            'heading' => __( 'Icon', 'js_composer' ),
            'param_name' => 'icon_typicons',
            'value' => 'typcn typcn-adjust-brightness',
            // default value to backend editor admin_label
            'settings' => array(
                'emptyIcon' => false,
                // default true, display an "EMPTY" icon?
                'type' => 'typicons',
                'iconsPerPage' => 4000,
                // default 100, how many icons per/page to display
            ),
            'dependency' => array(
                'element' => 'icon_type',
                'value' => 'typicons',
            ),
            'description' => __( 'Select icon from library.', 'js_composer' ),
            "group"			=> "Button",
        ),
        array(
            'type' => 'iconpicker',
            'heading' => __( 'Icon', 'js_composer' ),
            'param_name' => 'icon_entypo',
            'value' => 'entypo-icon entypo-icon-note',
            // default value to backend editor admin_label
            'settings' => array(
                'emptyIcon' => false,
                // default true, display an "EMPTY" icon?
                'type' => 'entypo',
                'iconsPerPage' => 4000,
                // default 100, how many icons per/page to display
            ),
            'dependency' => array(
                'element' => 'icon_type',
                'value' => 'entypo',
            ),
            'description' => __( 'Select icon from library.', 'js_composer' ),
            "group"			=> "Button",
        ),
        array(
            'type' => 'iconpicker',
            'heading' => __( 'Icon', 'js_composer' ),
            'param_name' => 'icon_linecons',
            'value' => 'vc_li vc_li-heart',
            // default value to backend editor admin_label
            'settings' => array(
                'emptyIcon' => false,
                // default true, display an "EMPTY" icon?
                'type' => 'linecons',
                'iconsPerPage' => 4000,
                // default 100, how many icons per/page to display
            ),
            'dependency' => array(
                'element' => 'icon_type',
                'value' => 'linecons',
            ),
            'description' => __( 'Select icon from library.', 'js_composer' ),
            "group"			=> "Button",
        ),
        array(
            'type' => 'iconpicker',
            'heading' => __( 'Icon', 'js_composer' ),
            'param_name' => 'icon_monosocial',
            'value' => 'vc-mono vc-mono-fivehundredpx',
            // default value to backend editor admin_label
            'settings' => array(
                'emptyIcon' => false,
                // default true, display an "EMPTY" icon?
                'type' => 'monosocial',
                'iconsPerPage' => 4000,
                // default 100, how many icons per/page to display
            ),
            'dependency' => array(
                'element' => 'icon_type',
                'value' => 'monosocial',
            ),
            'description' => __( 'Select icon from library.', 'js_composer' ),
            "group"			=> "Button",
        ),
        array(
            'type' => 'iconpicker',
            'heading' => __( 'Icon', 'js_composer' ),
            'param_name' => 'icon_material',
            'value' => 'vc-material vc-material-cake',
            // default value to backend editor admin_label
            'settings' => array(
                'emptyIcon' => false,
                // default true, display an "EMPTY" icon?
                'type' => 'material',
                'iconsPerPage' => 4000,
                // default 100, how many icons per/page to display
            ),
            'dependency' => array(
                'element' => 'icon_type',
                'value' => 'material',
            ),
            'description' => __( 'Select icon from library.', 'js_composer' ),
            "group"			=> "Button",
        ),
        array(
            "type"			=> "mgt_separator",
            "param_name"	=> generate_separator_name(),
            "heading"		=> "Button animation and effects",
            "group"			=> "Button",
        ),
        array(
            "type"			=> "dropdown",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Show button on block hover",
            "param_name"	=> "button_show_onhover",
            "value"			=> array(
                "No (Show button always)"	=> "0",
                "Yes (Hide button by default)"	=> "1"
            ),
            "description"	=> "Enable this to show button only on hover.",
            "std"			=> "0",
            "group"			=> "Button",
        ),
        array(
            "type"			=> "dropdown",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Button hover effect",
            "param_name"	=> "hover_effect",
            "value"			=> array(
                "Default"	=> "default",
                "[Shape] Grow"	=> "grow",
                "[Shape] Shrink"	=> "shrink",
                "[Shape] Pulse"	=> "pulse",
                "[Shape] Pulse Grow"	=> "pulse-grow",
                "[Shape] Pulse Shrink"	=> "pulse-shrink",
                "[Shape] Push"	=> "push",
                "[Shape] Pop"	=> "pop",
                "[Shape] Bounce In"	=> "bounce-in",
                "[Shape] Bounce Out"	=> "bounce-out",
                "[Shape] Rotate"	=> "rotate",
                "[Shape] Grow Rotate"	=> "grow-rotate",
                "[Shape] Float"	=> "float",
                "[Shape] Sink"	=> "sink",
                "[Shape] Bob"	=> "bob",
                "[Shape] Hang"	=> "hang",
                "[Shape] Skew"	=> "skew",
                "[Shape] Skew Forward"	=> "skew-forward",
                "[Shape] Skew Backward"	=> "skew-backward",
                "[Shape] Wobble Horizontal"	=> "wobble-horizontal",
                "[Shape] Wobble Vertical"	=> "wobble-vertical",
                "[Shape] Wobble To Bottom Right"	=> "wobble-to-bottom-right",
                "[Shape] Wobble To Top Right"	=> "wobble-to-top-right",
                "[Shape] Wobble Top"	=> "wobble-top",
                "[Shape] Wobble Bottom"	=> "wobble-bottom",
                "[Shape] Wobble Skew"	=> "wobble-skew",
                "[Shape] Buzz"	=> "buzz",
                "[Shape] Buzz Out"	=> "buzz-out",

                "[Background] Sweep To Right"	=> "sweep-to-right",
                "[Background] Sweep To Left"	=> "sweep-to-left",
                "[Background] Sweep To Bottom"	=> "sweep-to-bottom",
                "[Background] Sweep To Top"	=> "sweep-to-top",
                "[Background] Bounce To Right"	=> "bounce-to-right",
                "[Background] Bounce To Left"	=> "bounce-to-left",
                "[Background] Bounce To Bottom"	=> "bounce-to-bottom",
                "[Background] Bounce To Top"	=> "bounce-to-top",

                "[Icon] Icon Back"	=> "icon-back",
                "[Icon] Icon Forward"	=> "icon-forward",
                "[Icon] Icon Down"	=> "icon-down",
                "[Icon] Icon Up"	=> "icon-up",
                "[Icon] Icon Spin"	=> "icon-spin",
                "[Icon] Icon Drop"	=> "icon-drop",
                "[Icon] Icon Grow"	=> "icon-grow",
                "[Icon] Icon Shrink"	=> "icon-shrink",
                "[Icon] Icon Pulse"	=> "icon-pulse",
                "[Icon] Icon Pulse Grow"	=> "icon-pulse-grow",
                "[Icon] Icon Pulse Shrink"	=> "icon-pulse-shrink",
                "[Icon] Icon Push"	=> "icon-push",
                "[Icon] Icon Pop"	=> "icon-pop",
                "[Icon] Icon Bounce"	=> "icon-bounce",
                "[Icon] Icon Rotate"	=> "icon-rotate",
                "[Icon] Icon Grow Rotate"	=> "icon-grow-rotate",
                "[Icon] Icon Float"	=> "icon-float",
                "[Icon] Icon Sink"	=> "icon-sink",
                "[Icon] Icon Bob"	=> "icon-bob",
                "[Icon] Icon Hang"	=> "icon-hang",
                "[Icon] Icon Wobble Horizontal"	=> "icon-wobble-horizontal",
                "[Icon] Icon Wobble Vertical"	=> "icon-wobble-vertical",
                "[Icon] Icon Buzz"	=> "icon-buzz",
                "[Icon] Icon Buzz Out"	=> "icon-buzz-out",
            ),
            "description"	=> "Change button hover effect (<a href='http://ianlunn.github.io/Hover/' target='_blank'>Preview effects</a>). Please note that some effects works only for regular button styles, without style overrides and round edges.",
            "std"			=> "default",
            "group"			=> "Button",
        ),
        /* Button custom styles */
        array(
            "type"			=> "mgt_separator",
            "param_name"	=> generate_separator_name(),
            "heading"		=> "Button custom styles",
            "group"			=> "Button",
        ),
        array(
            'type' => 'checkbox',
            'heading' => __( 'Override this button styles?', 'js_composer' ),
            'param_name' => 'button_override',
            "description"	=> "Click and scroll down to show advanced button styles options. Please note that custom styled buttons and gradients backgrounds does not support all Button hover effect styles.",
            "group"			=> "Button",
        ),
        array(
            "type"			=> "dropdown",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Button font weight",
            "param_name"	=> "fontweight",
            "value"			=> array(
                "Normal"	=> "normal",
                "Bold"	=> "bold",
                "100"	=> "100",
                "200"	=> "200",
                "300"	=> "300",
                "400"	=> "400",
                "500"	=> "500",
                "600"	=> "600",
                "700"	=> "700",
                "800"	=> "800",
                "900"	=> "900"
            ),
            "group"			=> "Custom Styles",
            "description"	=> "Make sure you loaded font weight that you selected in Google Fonts settings for Header font in Theme Control Panel.",
            "std"			=> "normal",
            "group"			=> "Button",
            'dependency' => array(
                'element' => 'button_override',
                'value' => 'true',
            ),
        ),
        array(
            "type"			=> "colorpicker",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Button background color",
            "param_name"	=> "button_color_bg",
            "description"	=> "Override button background color.",
            "group"			=> "Button",
            "std"			=> "",
            'dependency' => array(
                'element' => 'button_override',
                'value' => 'true',
            ),
        ),
        array(
            'type' => 'checkbox',
            'heading' => __( 'Add gradient to button background color?', 'js_composer' ),
            'param_name' => 'button_bg_grad',
            "description"	=> "Use this to add second gradient color for button background.",
            "group"			=> "Button",
            'dependency' => array(
                'element' => 'button_override',
                'value' => 'true',
            ),
        ),
        array(
            "type"			=> "colorpicker",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Button background second color for gradient",
            "param_name"	=> "button_color_bggrad",
            "description"	=> "Override button background color for gradient.",
            "group"			=> "Button",
            "std"			=> "",
            'dependency' => array(
                'element' => 'button_bg_grad',
                'value' => 'true',
            ),
        ),
        array(
            "type"			=> "colorpicker",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Button hover background color",
            "param_name"	=> "button_color_bghover",
            "description"	=> "Override button hover background color.",
            "group"			=> "Button",
            "std"			=> "",
            'dependency' => array(
                'element' => 'button_override',
                'value' => 'true',
            ),
        ),
        array(
            'type' => 'checkbox',
            'heading' => __( 'Add gradient to button hover background color?', 'js_composer' ),
            'param_name' => 'button_bghover_grad',
            "description"	=> "Use this to add second gradient color for button hover background.",
            "group"			=> "Button",
            'dependency' => array(
                'element' => 'button_override',
                'value' => 'true',
            ),
        ),
        array(
            "type"			=> "colorpicker",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Button hover background second color for gradient",
            "param_name"	=> "button_color_bghovergrad",
            "description"	=> "Override button hover background color for gradient.",
            "group"			=> "Button",
            "std"			=> "",
            'dependency' => array(
                'element' => 'button_bghover_grad',
                'value' => 'true',
            ),
        ),
        array(
            "type"			=> "colorpicker",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Button text color",
            "param_name"	=> "button_color_text",
            "description"	=> "Override button text color.",
            "group"			=> "Button",
            "std"			=> "",
            'dependency' => array(
                'element' => 'button_override',
                'value' => 'true',
            ),
            "edit_field_class" => "vc_col-xs-6",
        ),
        array(
            "type"			=> "colorpicker",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Button hover text color",
            "param_name"	=> "button_color_texthover",
            "description"	=> "Override button hover text color.",
            "group"			=> "Button",
            "std"			=> "",
            'dependency' => array(
                'element' => 'button_override',
                'value' => 'true',
            ),
            "edit_field_class" => "vc_col-xs-6",
        ),
        array(
            'type' => 'checkbox',
            'heading' => __( 'Enable button border?', 'js_composer' ),
            'param_name' => 'button_border',
            "description"	=> "Use this to add solid border to button.",
            "group"			=> "Button",
            'dependency' => array(
                'element' => 'button_override',
                'value' => 'true',
            ),
        ),
        array(
            "type"			=> "textfield",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Border width (in pixels)",
            "description"	=> "Add border width here, for example: 3",
            "param_name"	=> "button_border_width",
            "group"			=> "Button",
            "std"			=> "2",
            'dependency' => array(
                'element' => 'button_border',
                'value' => 'true',
            ),
        ),
        array(
            "type"			=> "colorpicker",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Button border color",
            "param_name"	=> "button_color_border",
            "description"	=> "Override button border color.",
            "group"			=> "Button",
            "std"			=> "",
            'dependency' => array(
                'element' => 'button_border',
                'value' => 'true',
            ),
            "edit_field_class" => "vc_col-xs-6",
        ),
        array(
            "type"			=> "colorpicker",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "Button hover border color",
            "param_name"	=> "button_color_borderhover",
            "description"	=> "Override button hover border color.",
            "group"			=> "Button",
            "std"			=> "",
            'dependency' => array(
                'element' => 'button_border',
                'value' => 'true',
            ),
            "edit_field_class" => "vc_col-xs-6",
        ),
        /* Block format */
        array(
            "type"			=> "mgt_separator",
            "param_name"	=> generate_separator_name(),
            "heading"		=> "Override block content elements styles",
            "group"			=> "Format",
        ),
        array(
            "type"			=> "textfield",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "&lt;H1&gt; tag font size",
            "description"	=> "For ex.: 25px",
            "param_name"	=> "format_h1_fontsize",
            "group"			=> "Format",
            "std"			=> "",
        ),
        array(
            "type"			=> "textfield",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "&lt;H1&gt; margin",
            "description"	=> "For ex.: 0 0 30px 0",
            "param_name"	=> "format_h1_margin",
            "group"			=> "Format",
            "std"			=> "",
        ),
        array(
            "type"			=> "colorpicker",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "&lt;H1&gt; tag text color",
            "param_name"	=> "format_h1_color",
            "description"	=> "Override tag text color for this block.",
            "group"			=> "Format",
            "std"			=> "",
        ),
        array(
            "type"			=> "textfield",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "&lt;H2&gt; tag font size",
            "description"	=> "For ex.: 20px",
            "param_name"	=> "format_h2_fontsize",
            "group"			=> "Format",
            "std"			=> "",
        ),
        array(
            "type"			=> "textfield",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "&lt;H2&gt; margin",
            "description"	=> "For ex.: 0 0 20px 0",
            "param_name"	=> "format_h2_margin",
            "group"			=> "Format",
            "std"			=> "",
        ),
        array(
            "type"			=> "colorpicker",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "&lt;H2&gt; tag text color",
            "param_name"	=> "format_h2_color",
            "description"	=> "Override tag text color for this block.",
            "group"			=> "Format",
            "std"			=> "",
        ),
        array(
            "type"			=> "textfield",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "&lt;H3&gt; tag font size",
            "description"	=> "For ex.: 15px",
            "param_name"	=> "format_h3_fontsize",
            "group"			=> "Format",
            "std"			=> "",
        ),
        array(
            "type"			=> "textfield",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "&lt;H3&gt; margin",
            "description"	=> "For ex.: 0 0 10px 0",
            "param_name"	=> "format_h3_margin",
            "group"			=> "Format",
            "std"			=> "",
        ),
        array(
            "type"			=> "colorpicker",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "&lt;H3&gt; tag text color",
            "param_name"	=> "format_h3_color",
            "description"	=> "Override tag text color for this block.",
            "group"			=> "Format",
            "std"			=> "",
        ),
        array(
            "type"			=> "textfield",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "&lt;P&gt; tag font size",
            "description"	=> "For ex.: 12px",
            "param_name"	=> "format_p_fontsize",
            "group"			=> "Format",
            "std"			=> "",
        ),
        array(
            "type"			=> "textfield",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "&lt;P&gt; margin",
            "description"	=> "For ex.: 0 0 5px 0",
            "param_name"	=> "format_p_margin",
            "group"			=> "Format",
            "std"			=> "",
        ),
        array(
            "type"			=> "colorpicker",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "&lt;P&gt; tag text color",
            "param_name"	=> "format_p_color",
            "description"	=> "Override tag text color for this block.",
            "group"			=> "Format",
            "std"			=> "",
        ),
        array(
            "type"			=> "colorpicker",
            //"holder"		=> "div",
            "class" 		=> "hide_in_vc_editor",
            "admin_label" 	=> false,
            "heading"		=> "&lt;A&gt; link tag text color",
            "param_name"	=> "format_a_color",
            "description"	=> "Override tag text color for this block.",
            "group"			=> "Format",
            "std"			=> "",
        ),
        array(
            "type" => "textfield",
            "heading" => esc_attr__("Extra class name", 'asvc'),
            "param_name" => "el_class",
            "description" => esc_attr__("If you wish to style particular content element differently, then use this field to add a class name and then refer to it in your css file.", 'asvc')
        ),        
        array(
            'type' => 'css_editor',
            'heading' => __( 'Css' ),
            'param_name' => 'css',
            'group' => __( 'Content Design options' ),
        ),
        
    )

    
));




function asvc_shortcode_promo_block_wp($atts, $sc_content = null) {
    extract(shortcode_atts(array(
        /* General */
        'background_color' => '#F5F5F5',
        'darken' => 'no-darken',
        'darken_overlay_color' => 'rgba(0,0,0,0.3)',
        'animated' => 0,
        'animated_overlay_color' => 'rgba(0,0,0,0.5)',
        'background_image_id' => '',
        'background_repeat' => 'no-repeat',
        'coverimage' => 0,
        'parallax' => '',
        'parallax_speed' => 1.5,
        'video_bg' => false,
        'video_bg_url' => 'https://www.youtube.com/watch?v=lMJXxhRFO1k',
        'block_border' => false,
        'block_border_width' => 1,
        'block_border_style' => 'solid',
        'block_color_border' => '',
        'block_color_borderhover' => '',
        'block_height' => '',
        'content_va' => 'middle',
        'text_color' => 'black',
        'text_color_hover' => 0,
        'block_url'	=> '',
        'block_url_target_blank' => false,
        'css_animation' => 'none',
        /* Top Image */
        'top_image_enable' => false,
        'top_image_id' => '',
        'top_image_background_color' => '',
        'top_image_background_size' => 'cover',
        'top_image_height' => '',
        'top_image_url' => '',
        /* Button */
        'button_url' => '',
        'button_link_lightbox' => false,
        'button_style' => 'solid',
        'button_round_edges' => 'disable',
        'button_size' => 'normal',
        'button_align' => 'center',
        'button_text_size' => 'normal',
        'button_text_transform' => 'none',
        'button_top_margin' => false,
        // Icon
        'button_icon' => false,
        'button_icon_position' => 'left',
        'button_icon_separator' => false,
        'icon_type' => 'fontawesome',
        'icon_fontawesome' => 'fa fa-adjust',
        'icon_pe7stroke' => 'pe-7s-album',
        'icon_openiconic' => 'vc-oi vc-oi-dial',
        'icon_typicons' => 'typcn typcn-adjust-brightness',
        'icon_entypo' => 'entypo-icon entypo-icon-note',
        'icon_linecons' => 'vc_li vc_li-heart',
        'icon_monosocial' => 'vc-mono vc-mono-fivehundredpx',
        'icon_material' => 'vc-material vc-material-cake',
        // Animation
        'button_show_onhover' => 0,
        'hover_effect' => 'default',
        /* Button custom styles */
        'button_override' => false,
        'fontweight' => 'normal',
        'button_color_bg' => '',
        'button_bg_grad' => false,
        'button_color_bggrad' => '',
        'button_color_bghover' => '',
        'button_bghover_grad' => false,
        'button_color_bghovergrad' => '',
        'button_color_text' => '',
        'button_color_texthover' => '',
        'button_border' => false,
        'button_border_width' => 2,
        'button_color_border' => '',
        'button_color_borderhover' => '',
        /* Block format */
        'format_h1_fontsize' => '',
        'format_h1_margin' => '',
        'format_h1_color' => '',
        'format_h2_fontsize' => '',
        'format_h2_margin' => '',
        'format_h2_color' => '',
        'format_h3_fontsize' => '',
        'format_h3_margin' => '',
        'format_h3_color' => '',
        'format_p_fontsize' => '',
        'format_p_margin' => '',
        'format_p_color' => '',
        'format_a_color' => '',
        /* CSS */
        'block_shadow_effect' => false,
        'block_hover_effect' => false,
        'block_content_onhover' => false,
        'el_class' => '',
        'css' => '',
    ), $atts));
     
    
    ob_start();

    echo '<h3>This addon for pro version. Please buy <a href="https://codenpy.com/item/visual-composer-shortcodes-pro/">pro version from here</a></h3>';

    $sc_content = ob_get_contents();
    ob_end_clean();
    return $sc_content;
}

add_shortcode("asvc_promo_block", "asvc_shortcode_promo_block_wp");